# Réalisation d'un vecteur aléatoire Gaussien

In [48]:
import numpy as np
import matplotlib.pyplot as plt

In [49]:
x1 = np.random.uniform(0,1,1)
x2 = np.random.uniform(0,1,1)

z1 = np.sqrt(-2*np.log(x1)) * np.cos(2 * np.pi * x2)
z2 = np.sqrt(-2*np.log(x1)) * np.sin(2 * np.pi * x2)

Z = np.array([z1, z2])
Z

array([[1.91474822],
       [0.12976531]])

In [50]:
m = np.array([6,7])

In [51]:
K = np.array([[18, 15], [15, 16]])

In [52]:
C = np.linalg.cholesky(K)

In [53]:
C

array([[4.24264069, 0.        ],
       [3.53553391, 1.87082869]])

In [54]:
Y = C*Z + m
Y

array([[14.12358869,  7.        ],
       [ 6.45878965,  7.24276866]])